# Generated by Django 4.1.3 on 2022-12-07 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sustainee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(editable=False, max_length=255)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Refresh Token',
                'verbose_name_plural': 'User Refresh Tokens',
                'abstract': False,
                'unique_together': {('token', 'revoked')},
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
