# Generated by Django 4.1.3 on 2022-12-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainee', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
