# Generated by Django 4.1.3 on 2022-12-09 15:48

from django.db import migrations
import sustainee.models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainee', '0005_alter_customuser_email_alter_signup_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', sustainee.models.CustomUserManager()),
            ],
        ),
    ]
