# Generated by Django 4.1.3 on 2022-12-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainee', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
